server:
   port: 8888
spring:
   application:
      name: friennect-cloud-config-service
   cloud:
      config:
         server:
            git:
               uri: https://github.com/friennect-cloud-config
               search-paths:
               - configuration
      